ALTER TABLE public."Parameter" ADD "DrivingWithoutSeatBelt" boolean NULL DEFAULT FALSE;
ALTER TABLE public."Parameter" ADD "DrivingWhileOnTheMobile" boolean NULL DEFAULT FALSE;
ALTER TABLE public."EventLogs" ADD "NoSeatBelt" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE public."EventLogs" ADD "IsDrivingWhileOnTheMobile" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE public."EventLogs" ADD "IsNotValid" boolean NOT NULL DEFAULT FALSE;
CREATE TABLE public."ChallanDetails" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Address" text NULL,
    "EmailId" text NULL,
    "PhoneNumber" text NULL,
    "DeliveryStatus" text NULL,
    "PaymentStatus" text NULL,
    "EventLogsId" integer NOT NULL,
    CONSTRAINT "PK_ChallanDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChallanDetails_EventLogs_EventLogsId" FOREIGN KEY ("EventLogsId") REFERENCES public."EventLogs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChallanDetails_EventLogsId" ON public."ChallanDetails" ("EventLogsId");
