
ALTER TABLE public."Resources" ADD "AnalyticServerId" integer NULL;
CREATE TABLE public."AnalyticServers" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AnalyticServerIp" text NULL,
    "AnalyticServerPort" integer NOT NULL,
    "AnalyticStreamingPort" integer NOT NULL,
    "AnalyticServerName" text NULL,
    "AnalyticEventListeningPort" integer NOT NULL,
    "isDefault" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_AnalyticServers" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Resources_AnalyticServerId" ON public."Resources" ("AnalyticServerId");

ALTER TABLE public."Resources" ADD CONSTRAINT "FK_Resources_AnalyticServers_AnalyticServerId" FOREIGN KEY ("AnalyticServerId") REFERENCES public."AnalyticServers" ("Id") ON DELETE RESTRICT;
ALTER TABLE public."Resources" ADD "radarEventZoneId" integer NULL;
ALTER TABLE public."AnalyticServers" ADD "subscribeEventsFromRabbitMQ" boolean NOT NULL DEFAULT FALSE,

INSERT INTO  public."AnalyticServers" ("AnalyticServerIp","AnalyticServerPort","AnalyticStreamingPort","AnalyticServerName","AnalyticEventListeningPort","isDefault","subscribeEventsFromRabbitMQ") 
VALUES ('127.0.0.1',5000,8080,'localhost',5001,TRUE,FALSE)
where  (select count(*) < 1);

UPDATE public."Resources" SET "AnalyticServerId" = 1 WHERE "Discriminator" = 'Camera';