CREATE TABLE public."AnalyticServerLogs" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AnalyticServerId" integer NOT NULL,
    "ServerStatus" text  NOT NULL,
    "LogDate" bigint NOT NULL,
    "AnalyticServerName" text NULL,
    CONSTRAINT "PK_AnalyticServerLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AnalyticServerLogs_AnalyticServers_AnalyticServerId" FOREIGN KEY ("AnalyticServerId") REFERENCES public."AnalyticServers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AnalyticServerLogs_AnalyticServerId" ON public."AnalyticServerLogs" ("AnalyticServerId");

ALTER TABLE public."ResourceAnalytics" ADD "CapValue" text NULL DEFAULT 'CAP1';

ALTER TABLE public."Parameter" ADD "CheckForRedLightViolationInThisCamera" boolean NULL DEFAULT FALSE;

CREATE TABLE public."UsedPassword" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "HashPasswords" text[] NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_UsedPassword" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UsedPassword_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
);
