ALTER TABLE public."Parameter" DROP COLUMN "NumberOfImagesToSave";
ALTER TABLE public."Parameter" DROP COLUMN "CamAssociated";
ALTER TABLE public."Parameter" DROP COLUMN "AssociatedCamId";
ALTER TABLE public."Parameter" DROP COLUMN "FrameIntervalBetweenImagesToSave";

ALTER TABLE public."Parameter" ADD "AnprPreviousImagesToSave" integer NULL DEFAULT 0;
ALTER TABLE public."Parameter" ADD "AnprForwardImagesToSave" integer NULL DEFAULT 0;
ALTER TABLE public."Parameter" ADD "AnprFrameIntervalBetweenImagesToSave" integer NULL DEFAULT 5;

CREATE TABLE public."AssociatedCamDetails" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AssociatedCamId" integer NOT NULL,
    "AssociatedAnalyticName" text NULL,
    "PreviousImagesToSave" integer NOT NULL,
    "ForwardImagesToSave" integer NOT NULL,
    "FrameIntervalBetweenImages" integer NOT NULL,
    "ANPRParameterId" integer NOT NULL,
    CONSTRAINT "PK_AssociatedCamDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AssociatedCamDetails_Parameter_ANPRParameterId" FOREIGN KEY ("ANPRParameterId") REFERENCES public."Parameter" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AssociatedCamDetails_ANPRParameterId" ON public."AssociatedCamDetails" ("ANPRParameterId");

ALTER TABLE public."EventLogs" DROP COLUMN "_AttachedImages";
ALTER TABLE public."EventLogs" ADD "AttachedImgPaths" text[] NULL;