ALTER TABLE public."Resources" DROP COLUMN "SetStatusByPing";
ALTER TABLE public."Resources" DROP COLUMN "checkViolation";

ALTER TABLE public."Resources" DROP COLUMN "speedLimit";
ALTER TABLE public."EventLogs" ADD "WrongDirectionDetected" boolean NULL DEFAULT FALSE;
ALTER TABLE public."EventLogs" ADD "StoppedVehicleDetected" boolean NULL DEFAULT FALSE;

ALTER TABLE public."Resources" ADD "SetStatusByPing" text NULL DEFAULT 'AnalyticsNotApplied';
CREATE TABLE event_changes_log (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id integer NOT NULL,
    column_name text NULL,
    old_value text NULL,
    new_value text NULL,
    change_date TIMESTAMP DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION event_log_change()
    RETURNS TRIGGER AS $$
DECLARE
    column_name TEXT;
    old_value TEXT;
    new_value TEXT;
	columns CURSOR FOR SELECT '"PlateNumber"' UNION SELECT '"VehicleType"' UNION SELECT '"VehicleColor"';
BEGIN
    -- Define the list of columns to log changes
     -- Open the cursor
    OPEN columns;

    -- Iterate over the cursor
    LOOP
        FETCH NEXT FROM columns INTO column_name;
        EXIT WHEN NOT FOUND;
		EXECUTE 'SELECT ($1).' || column_name || '::text' INTO new_value USING NEW;
        EXECUTE 'SELECT ($1).' || column_name || '::text' INTO old_value USING OLD;

        -- Insert log entry if the value has changed
        IF new_value IS DISTINCT FROM old_value THEN
            INSERT INTO event_changes_log (event_id,column_name, old_value, new_value)
            VALUES (OLD."Id",column_name,old_value, new_value);
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER changes_trigger
    AFTER UPDATE OF "PlateNumber", "VehicleType", "VehicleColor" ON public."EventLogs"
    FOR EACH ROW
    EXECUTE FUNCTION event_log_change();