ALTER TABLE public."AnalyticServers"
    ADD CONSTRAINT UQ_AnalyticServers_IpPort UNIQUE ("AnalyticServerIp", "AnalyticServerPort");

CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TABLE public."PendingEventIntegrationData" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
  "RegNo" text NOT NULL,
  "EventProperties" hstore NULL,
  "TriggerTime" bigint NOT NULL,
  "ResourceName" text NULL,
  "IsTriggeredBeforeItmsEvent" boolean NULL,
  "TimeDifferenceRange" bigint NULL,
  CONSTRAINT "PK_PendingEventIntegrationData" PRIMARY KEY ("Id")
);
ALTER TABLE public."ChallanDetails" ADD "AnprViolationVideo" text NULL;
