ALTER TABLE public."EventLogs" ADD "DiscardedEvent" boolean NULL DEFAULT FALSE;
ALTER TABLE public."Resources" ADD "ResourceGroupId" integer NOT NULL DEFAULT 1;
CREATE SEQUENCE public."ResourceGroupId" START WITH 2 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE TABLE public."ResourceGroups" (
    "Id" integer NOT NULL DEFAULT (nextval('public."ResourceGroupId"')),
    "GroupName" text NULL,
    CONSTRAINT "PK_ResourceGroups" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Resources_ResourceGroupId" ON public."Resources" ("ResourceGroupId");
INSERT INTO public."ResourceGroups"(
	"Id", "GroupName")
	VALUES (1, 'Not Mapped');
ALTER TABLE public."Resources" ADD CONSTRAINT "FK_Resources_ResourceGroups_ResourceGroupId" FOREIGN KEY ("ResourceGroupId") REFERENCES public."ResourceGroups" ("Id") ON DELETE RESTRICT;


ALTER TABLE public."ChallanDetails" ADD "ChallanTriggerTime" bigint NOT NULL DEFAULT 0;

ALTER TABLE public."ChallanDetails" ADD "UserId" integer NOT NULL DEFAULT 100;
ALTER TABLE public."ChallanDetails" ADD "Violations" text[];

CREATE INDEX "IX_ChallanDetails_UserId" ON public."ChallanDetails" ("UserId");

ALTER TABLE public."ChallanDetails" ADD CONSTRAINT "FK_ChallanDetails_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE RESTRICT;


CREATE TABLE public."CameraViolationCountMetaData" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CameraId" integer NOT NULL,
    "Violation" text NULL,
    "ViolationCount" integer NOT NULL,
    "eventDate" timestamp WITHOUT TIME ZONE NULL,
    "LastRowTraversedEventId" integer NOT NULL,
    "AreaName" text NULL,
    CONSTRAINT "PK_CameraViolationCountMetaData" PRIMARY KEY ("Id")
);




CREATE INDEX IF NOT EXISTS idx_eventlogs_detime ON public."EventLogs" ("DetTime");

ALTER TABLE public."CameraViolationCountMetaData" DROP COLUMN "AreaName";

ALTER TABLE public."CameraViolationCountMetaData" DROP COLUMN "CameraId";

ALTER TABLE public."CameraViolationCountMetaData" DROP COLUMN "LastRowTraversedEventId";

ALTER TABLE public."CameraViolationCountMetaData" DROP COLUMN "Violation";

ALTER TABLE public."CameraViolationCountMetaData" DROP COLUMN "ViolationCount";

ALTER TABLE public."CameraViolationCountMetaData" DROP COLUMN "eventDate";

ALTER TABLE public."CameraViolationCountMetaData" ADD "DetTime" bigint NOT NULL DEFAULT 0;

ALTER TABLE public."CameraViolationCountMetaData" ADD "_ViolationDataAsPerDevice" text NULL;

CREATE TABLE public."CmsImageDownloadFailure" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "AnprId" integer NOT NULL,
    CONSTRAINT "PK_CmsImageDownloadFailure" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CmsImageDownloadFailure_EventLogs_EventId" FOREIGN KEY ("EventId") REFERENCES public."EventLogs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CmsImageDownloadFailure_EventId" ON public."CmsImageDownloadFailure" ("EventId");