CREATE TABLE public."CommonCategoryAttributes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AttributeName" text NULL,
    CONSTRAINT "PK_CommonCategoryAttributes" PRIMARY KEY ("Id")
);


DROP TABLE public."Actions";

DROP TABLE public."Rule";

DROP TABLE public."RuleSet";

ALTER TABLE public."ActionData" DROP COLUMN "Name";

ALTER TABLE public."ActionData" ADD "ActionNamesId" integer NOT NULL DEFAULT 0;

ALTER TABLE public."ActionData" ADD "_Actions" text NULL;

ALTER TABLE public."ActionData" ADD "_RuleSet" text NULL;

CREATE TABLE public."ActionNames" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "IsPredefinedAction" boolean NOT NULL,
    CONSTRAINT "PK_ActionNames" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_ActionData_ActionNamesId" ON public."ActionData" ("ActionNamesId");

ALTER TABLE public."ActionData" ADD CONSTRAINT "FK_ActionData_ActionNames_ActionNamesId" FOREIGN KEY ("ActionNamesId") REFERENCES public."ActionNames" ("Id") ON DELETE CASCADE;

INSERT INTO public."ActionNames"( "Name", "IsPredefinedAction") VALUES ('Category', true);
INSERT INTO public."ActionData"("ActionNamesId", "_Actions", "_RuleSet") SELECT an."Id", '[{{"Id":0,"Discriminator":"PopupAction"}}]', '{{"Condition":"and","Rules":[{{"Field":"Category","Operator":"Contains","Value":"Wanted,Stolen,Lost,Suspecious,Authorized,Unauthorized","Type":1}}],"Ruleset":null}}' FROM public."ActionNames" an WHERE an."IsPredefinedAction" = true Limit 1